# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20161013_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='limit',
            field=models.DateTimeField(verbose_name='Time long'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(verbose_name='start event'),
        ),
    ]
