# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcomment',
            options={'ordering': ('post',)},
        ),
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ('user',)},
        ),
    ]
