# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20161129_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='date_create',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='date_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
